# Generated by Django 4.0.4 on 2022-06-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=100)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('senha', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=40)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='user_foto/%Y/%m/%d')),
            ],
        ),
    ]
