# Generated by Django 4.0.4 on 2022-06-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_foto_alter_user_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserNormal',
        ),
    ]
