# Generated by Django 4.0.4 on 2022-06-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_usernormal_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernormal',
            name='foto',
            field=models.ImageField(default='a', upload_to='user_foto/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
