# Generated by Django 4.0.4 on 2022-05-23 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='titulo',
            field=models.CharField(default='teste', max_length=50),
            preserve_default=False,
        ),
    ]
