# Generated by Django 4.0.4 on 2022-06-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='conteudo',
        ),
        migrations.AddField(
            model_name='novel',
            name='descricao',
            field=models.TextField(default='a', verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novel',
            name='escritor',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novel',
            name='ilustrador',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novel',
            name='outros_titulos',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novel',
            name='qdt_volumes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novel',
            name='status',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novel',
            name='titulo',
            field=models.CharField(default=1, max_length=50, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novel',
            name='wallpaper',
            field=models.ImageField(default=1, upload_to='novel_wall/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
