# Generated by Django 4.0.4 on 2022-06-05 17:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_remove_novel_conteudo_novel_descricao_novel_escritor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_vol', models.CharField(max_length=50)),
                ('capa_vol', models.ImageField(upload_to='vol_capa/%Y/%m/%d')),
                ('num_vol', models.IntegerField()),
                ('descriacao_vol', models.TextField()),
                ('data_vol', models.DateTimeField(default=django.utils.timezone.now)),
                ('novel_vol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.novel')),
            ],
        ),
    ]
