# Generated by Django 4.0.4 on 2022-05-25 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_novel_descricao_novel_volumes_alter_novel_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novel',
            old_name='volumes',
            new_name='volume',
        ),
    ]
