# Generated by Django 4.0.4 on 2022-06-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0004_novel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='slug_vol',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
