# Generated by Django 4.0.4 on 2022-06-06 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0004_volume_vol_vol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_cap', models.CharField(max_length=100)),
                ('conteudo_cap', models.TextField()),
                ('volume_cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.volume')),
            ],
        ),
    ]
