# Generated by Django 4.0.4 on 2022-05-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0004_rename_volumes_novel_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='wallpaper',
            field=models.ImageField(default='a', upload_to='novel_img/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
