# Generated by Django 4.0.4 on 2022-05-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0005_novel_wallpaper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novel',
            old_name='volume',
            new_name='volumes',
        ),
        migrations.AlterField(
            model_name='novel',
            name='wallpaper',
            field=models.ImageField(upload_to='novel_wall/%Y/%m/%d'),
        ),
    ]
