# Generated by Django 4.0.4 on 2022-06-06 03:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0005_capitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='data_cap',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
