# Generated by Django 4.0.4 on 2022-06-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0005_volume_slug_vol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volume',
            old_name='slug_vol',
            new_name='slug',
        ),
    ]
