# Generated by Django 4.0.4 on 2022-06-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0006_rename_slug_vol_volume_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='slug',
        ),
    ]
