# Generated by Django 4.0.4 on 2022-06-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0007_remove_volume_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='slug_vol',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
