# Generated by Django 4.0.4 on 2022-06-17 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0008_volume_slug_vol'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='slug_cap',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
