# Generated by Django 4.0.4 on 2022-05-30 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0008_capitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='novel_vol',
        ),
        migrations.DeleteModel(
            name='Capitulo',
        ),
        migrations.DeleteModel(
            name='Volume',
        ),
    ]
