# Generated by Django 4.0.4 on 2022-07-28 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0009_capitulo_slug_cap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='titulo_vol',
        ),
    ]
