# Generated by Django 4.0.4 on 2022-05-30 22:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0009_remove_volume_novel_vol_delete_capitulo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novel',
            old_name='volumes',
            new_name='qdt_volumes',
        ),
        migrations.RemoveField(
            model_name='novel',
            name='conteudo',
        ),
        migrations.AddField(
            model_name='novel',
            name='escritor',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novel',
            name='ilustrador',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novel',
            name='outros_titulos',
            field=models.CharField(default='a', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='novel',
            name='status',
            field=models.CharField(default='a', max_length=25),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_vol', models.CharField(max_length=50)),
                ('capa_vol', models.ImageField(upload_to='vol_capa/%Y/%m/%d')),
                ('num_vol', models.IntegerField()),
                ('descriacao_vol', models.TextField()),
                ('data_vol', models.DateTimeField(default=django.utils.timezone.now)),
                ('novel_vol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.novel')),
            ],
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_cap', models.CharField(max_length=100)),
                ('conteudo_cap', models.TextField()),
                ('volume_cap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.volume')),
            ],
        ),
    ]
