# Generated by Django 4.0.4 on 2022-07-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0010_remove_volume_titulo_vol'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='numero_cap',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
