# Generated by Django 4.0.4 on 2022-05-30 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0010_rename_volumes_novel_qdt_volumes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='conteudo',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='novel',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
