# Generated by Django 4.0.4 on 2022-06-01 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0011_novel_conteudo_alter_novel_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='conteudo',
        ),
    ]
