# Generated by Django 4.0.4 on 2022-07-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0012_alter_capitulo_numero_cap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='numero_cap',
            field=models.CharField(max_length=100),
        ),
    ]
