# Generated by Django 4.0.4 on 2022-06-02 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0012_remove_novel_conteudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volume',
            name='novel_vol',
        ),
        migrations.DeleteModel(
            name='Capitulo',
        ),
        migrations.DeleteModel(
            name='Volume',
        ),
    ]
